### PR TITLE
Updates for CakePHP 4.0

### PR DESCRIPTION
**Pull request by smap9**
Hey, this should be the update for CakePHP 4.0.

### CODE REVIEW

**Comment by smap9** [comment]
@chrisShick any chance to get this merged? Anything missing in the PR?

**Comment by josephshanak** [comment]
@chrisShick I'm also waiting on this.

**Comment by chrisShick** [comment]
@smap9 thanks for getting this updated! I will get this merged.

**Comment by chrisShick** [comment]
@smap9 can you recreate the pull request to branch 4.0? I will then merge and release it as a new version

**Comment by chrisShick** [comment]
@smap9 I was able to get this going! Thanks for putting the work in.

**Pull request closed without merging**
